// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwyEurKFlmnfPzfBkHavAIYpwRHu_65y4',
    appId: '1:113794843047:web:d6a3d2a0714f10b8a9f682',
    messagingSenderId: '113794843047',
    projectId: 'boogeraids-picklerick',
    authDomain: 'auth.letsboogyboogy.com',
    storageBucket: 'boogeraids-picklerick.appspot.com',
    measurementId: 'G-THTPWCT9FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7LDcMrItPILZXf8A953d3bjZx7WkpoiI',
    appId: '1:113794843047:android:019f54e8d6c7b072a9f682',
    messagingSenderId: '113794843047',
    projectId: 'boogeraids-picklerick',
    storageBucket: 'boogeraids-picklerick.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO8MObfOJOrbCxn6XdQfNVaCcB7ECNaoI',
    appId: '1:113794843047:ios:96279b48fd12667ca9f682',
    messagingSenderId: '113794843047',
    projectId: 'boogeraids-picklerick',
    storageBucket: 'boogeraids-picklerick.appspot.com',
    iosBundleId: 'com.boogeraids.picklerick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO8MObfOJOrbCxn6XdQfNVaCcB7ECNaoI',
    appId: '1:113794843047:ios:38011085180a4092a9f682',
    messagingSenderId: '113794843047',
    projectId: 'boogeraids-picklerick',
    storageBucket: 'boogeraids-picklerick.appspot.com',
    iosBundleId: 'com.boogeraids.picklerick.RunnerTests',
  );
}
